<?php

class Shape
{
    public string $name;

    public function __construct($name)
    {
        $this->name = $name;
    }

    public function show()
    {
        echo "my name is: " . $this->name;
    }
}

class Circle extends Shape
{
    public int $radius;

    public function __construct($name, $radius)
    {
        $this->radius = $radius;
        parent::__construct($name);
    }

    public function calculateArea(): int
    {
        return pow($this->radius, 2) * M_PI;
    }

    public function calculatePerimeter(): int
    {
        return $this->radius * 2 * M_PI;
    }
}

class Cylinder extends Circle
{
    public int $height;
    public function __construct($name, $radius, $height)
    {
        $this->height =$height;
        parent::__construct($name, $radius);
    }
    public function calculateArea(): int
    {
        return parent::calculateArea()*2 + parent::calculateArea()*$this->height; // TODO: Change the autogenerated stub
    }
    public function calculateVolumn(): int{
        return parent::calculateArea()*$this->height;
    }
}

class Rectangle extends Shape{
    public int $width;
    public int $height;
    public function __construct($name,$width,$height)
    {
        $this->height=$height;
        $this->width=$width;
        parent::__construct($name);
    }
    public function calculateArea():int{
        return ($this->width+$this->height)*2;
    }
    public function calculatePerimeter():int{
        return $this->height*$this->width;
    }
}

class Square extends Rectangle{

}